version: "3"

services:
  react-app:
    build: ./code
    container_name: react-app
    command: sh -c "cd my-app && npm run serve"
    volumes:
      - ./code/:/code
    ports:
      - '3000:3000'
      - '8080:8080'
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./code/my-app/docs/:/usr/share/nginx/html/
